test:test코드 추가
pilming44/EVERYTHING-SHOP pull request #73
Opened 2024-04-04 05:38 UTC by scodeda

DiscoutPolicy,PointHistory,ProductViews,User의 함수 테스트코드 추가

2024-04-05 02:23 UTC, pilming44 requested changes
테스트코드 만드느라 꽤 고생하셨겠는데요?? ㅋㅋㅋ 
하신거 보면서 들었던 생각 적어놨는데요! 확인해보시고 수정해서 다시 커밋해주세요~!

2024-04-05 02:23 UTC, pilming44 commented on src/test/java/study/toy/everythingshop/entity/mariaDB/DiscountPolicyTest.java
> +        }
테스트코드에서는 분기를 사용하지않는게 좋을것같아요.
나중에 다른사람이 봤을때 `@DisplayName`만 보고 이 테스트가 어떤 테스트인지 판단할수있어야되는데
조건문이 있다면 메인코드처럼 로직 해석하는데 추가적인 시간이 필요할것같아요.

이런 경우엔

- 할인 정책 변경된게 없다면 false
- 할인 정책의 할인률 변경 시 true
- 할인 정책 기본지급금액 변경 시 true

이렇게 테스트를 분리해보면 어떨까싶습니다!

그리고 테스트코드 작성의 의미가 오류를 방지하기위함이니까

할인률에 음수를 넣었을 경우, 문자를 넣었을 경우, 공백을 넣었을 경우 같은 예외상황에 대한 테스트도 필요할것같아요!

그럼 예외처리도 메인로직에 추가돼야겠네요! 리팩토링할거 넘쳐나는중... ㅋㅋㅋ

2024-04-05 02:23 UTC, pilming44 commented on src/test/java/study/toy/everythingshop/entity/mariaDB/PointHistoryTest.java
> +        pointHistory.reducePoint(paidPoints);
자주 사용될것같은 객체라면 `@BeforeEach`로 생성하면 어떨까요?

2024-04-05 02:23 UTC, pilming44 commented on src/test/java/study/toy/everythingshop/entity/mariaDB/PointHistoryTest.java
> +        assertThat(pointHistory.getPointChangeCd()).isEqualTo("03");
아래에서 테스트 했으니 여기선 검증하지않아도 되지않을까요? 🤔

2024-04-05 02:23 UTC, pilming44 commented on src/test/java/study/toy/everythingshop/entity/mariaDB/UserTest.java
> +        }
여기서도 조건문은 별도의 테스트로!

2024-04-05 02:23 UTC, pilming44 commented on src/test/java/study/toy/everythingshop/entity/mariaDB/UserTest.java
> +        assertThat(user.getHoldingPoint()).isEqualTo(holdingPrice+refundPrice);
환불테스트까지 꼼꼼하게 만들어주셨네요 👍

2024-04-05 02:42 UTC, pilming44 commented
다음 #74 에 포함돼있어서 이건 close하겠습니다!

2024-04-05 02:42 UTC, closed without merging

2024-04-13 01:30 UTC, scodeda commented on src/test/java/study/toy/everythingshop/entity/mariaDB/DiscountPolicyTest.java
> +        }
그럼 음수같은 예외 사항은 프론트단에서 입력을 못하게 막아야할거같은데 프론트단에서 받은 값을 테스트하는 건가요??