test: product 객체 테스트 코드 작성
pilming44/EVERYTHING-SHOP pull request #75
Opened 2024-04-06 06:38 UTC by lhe2001

getCurrentPrice는 중복, getRemainQuantity는 이미 db 칼럼에 추가되었길래 필요없는 코드로 보입니다. 두 method는 test 코드 작성하지 않았습니다.

2024-04-10 09:10 UTC, pilming44 requested changes

2024-04-10 09:10 UTC, pilming44 commented on src/test/java/study/toy/everythingshop/entity/ProductTest.java
> +
`getCurrentPrice()` 가 중복이라고하셨는데 어떤거하고 중복인가요???

2024-04-10 09:11 UTC, pilming44 requested changes
고생하셨습니다! 만들면서 테스트 초록불 들어올때 엄청 기분좋지않나요?? ㅋㅋ

2024-04-11 00:11 UTC, lhe2001 commented on src/main/java/study/toy/everythingshop/entity/mariaDB/ProductViews.java
> +@AllArgsConstructor
entity가 기본적으로 getter는 있는데, setter가 없다보니, 테스트코드 작성시에 getter를 넣어야하나란 고민이 많았어요. 그렇다고 매 테스트용 생성자를 만들기에도 고민..그래서 결론은 빌더를 썼습니다.

2024-04-11 00:12 UTC, lhe2001 commented on src/test/java/study/toy/everythingshop/entity/ProductTest.java
> +
결국은 discount된 가격을 가져오는 method 더라고요? 그래서 getDiscountPrice와 동일한 기능이었어요.

2024-04-11 01:05 UTC, pilming44 commented on src/main/java/study/toy/everythingshop/entity/mariaDB/ProductViews.java
> +@AllArgsConstructor
여기에 설명이 잘 돼있네요!
https://devlog-wjdrbs96.tistory.com/419
@Builder만 사용하면 자동으로 @AllArgsConstructor같은 전체 생성자를 만들어준다고하네여

그런데 jpa를 사용하면 기본 생성자가 필수니까 그럴때는 명시적으로 @Builder와 @AllArgsConstructor를 사용해줘야된대요

그래서 jpa를 쓰는 시스템에서 빌더를 쓰려면
@Builder
@NoArgsConstructor
@AllArgsConstructor
가 세트처럼 사용되겠네여

2024-04-11 01:09 UTC, pilming44 commented on src/test/java/study/toy/everythingshop/entity/ProductTest.java
> +
`getDiscountPrice()`는 할인가격을 가져오는거고
`getCurrentPrice()`는 할인가격이 적용된 할인 된 가격을 가져오는거 아닌가요??
원래가격 : 10000
할인가격 : 1000 -> `getDiscountPrice()`
할인된가격 : 9000 -> `getCurrentPrice()`

2024-04-14 10:05 UTC, pilming44 approved these changes
굿뜨

2024-04-14 10:05 UTC, merged